import assert from 'node:assert/strict';
import {newSites,listSites,hasPaidPlan} from '../netlify/functions/_shared/new-site.mts';
import handler,{seal,unseal} from '../netlify/functions/wordpress.mts';
globalThis.Netlify={env:{get:()=> 'test'.repeat(16)}};
const entries=new Map();
const store={set:async(k,v)=>{entries.set(k,v);},get:async(k)=>entries.get(k)};
const handle=req=>handler(req,{},()=>store);
const now=Date.now();
const site={ID:456,URL:'https://jamietest14.wpcomstaging.com',options:{created_at:new Date(now+1000).toISOString()},capabilities:{manage_options:true},plan:{is_free:false}};
assert.deepEqual(newSites([site],['456'],now),[]);
assert.equal(newSites([site],[],now)[0],site);
assert.equal(newSites([{...site,options:{created_at:'2000-01-01'}}],[],now).length,0);
assert.equal(newSites([{...site,options:{}}],[],now).length,0);
assert.equal(newSites([{...site,capabilities:{}}],[],now).length,0);
const base='https://playground-wpcom-connect.netlify.app';
const account={token:'test-token',flow:'flow',exp:now+60000};
const cookie='__Host-pgwpc-account='+seal(account);
const proof=seal({purpose:'watch',flow:'flow',exp:account.exp});
const req=(action,watch='',body={})=>new Request(base+'/api/new-site?action='+action,{method:'POST',headers:{cookie:cookie+'; '+watch,'x-pgwpc-watch':proof},body:JSON.stringify(body)});
globalThis.fetch=async url=>{const page=Number(new URL(url).searchParams.get('page'));return Response.json({sites:Array.from({length:100},(_,i)=>({...site,ID:10000+(page-1)*100+i})),total:2000});};
const prepared=await handle(req('prepare','',{name:'jamietest1'}));
assert.equal(prepared.status,200);
assert.ok(prepared.headers.get('set-cookie').length<1000);
const watch=prepared.headers.get('set-cookie').split(';')[0];
globalThis.fetch=async()=>Response.json({sites:[{...site,plan:{product_slug:'personal-bundle'}}],total:1});
const ready=await handle(req('poll',watch));
assert.equal((await ready.json()).ready,true);
const other={...site,ID:789,URL:'https://other.wpcomstaging.com'};
globalThis.fetch=async()=>Response.json({sites:[site,other],total:2});
const ambiguous=await handle(req('poll',watch));
assert.equal((await ambiguous.json()).choices.length,2);
const chosen=await handle(req('poll',watch,{siteId:'789'}));
assert.equal((await chosen.json()).blog,other.URL);
assert.equal((await handle(req('poll',watch,{siteId:'123'}))).status,409);
globalThis.fetch=async()=>Response.json({sites:[{...site,plan:{is_free:true}}],total:1});
assert.equal((await (await handle(req('poll',watch))).json()).waiting,true);
let page=0;
globalThis.fetch=async()=>Response.json(++page===1?{sites:[site],total:2}:{sites:[other],total:2});
assert.equal((await listSites('test')).length,2);
globalThis.fetch=async()=>Response.json({sites:[]});
await assert.rejects(()=>listSites('test'),/incomplete/);
const record=unseal(watch.split('=')[1]);
assert.equal(record.baseline,undefined);
assert.ok(record.baselineId);
entries.clear();
assert.equal((await handle(req('poll',watch))).status,400);
console.log('PASS: ID baseline, assigned staging address, old-site exclusion, ambiguity selection, forged selection rejection, plan waiting and pagination.');

assert.equal(hasPaidPlan({plan:{product_slug:'personal-bundle'}}),true);
assert.equal(hasPaidPlan({plan:{product_slug:'free_plan'}}),false);
assert.equal(hasPaidPlan({plan:{product_slug:'personal-bundle',expired:true}}),false);
assert.equal(hasPaidPlan({plan:{}}),false);
console.log('PASS: omitted is_free does not block a non-free plan; free, expired and unknown plans still wait.');
