import assert from 'node:assert/strict';
import { selectNewSite } from '../netlify/functions/_shared/new-site.mts';
import handler,{seal} from '../netlify/functions/wordpress.mts';
globalThis.Netlify={env:{get:()=> 'test'.repeat(16)}};
const now=Date.now(),expected='newsite.wordpress.com';
const site={ID:456,URL:'https://'+expected,options:{created_at:new Date(now+1000).toISOString()},capabilities:{manage_options:true},plan:{is_free:false}};
assert.equal(selectNewSite([],expected,now),null);
assert.equal(selectNewSite([{...site,URL:'https://other.wordpress.com'}],expected,now),null);
assert.equal(selectNewSite([site],expected,now),site);
assert.equal(selectNewSite([{...site,plan:{is_free:true}}],expected,now),null);
assert.throws(()=>selectNewSite([{...site,options:{created_at:new Date(now-1000).toISOString()}}],expected,now));
assert.throws(()=>selectNewSite([{...site,options:{}}],expected,now));
assert.throws(()=>selectNewSite([site,site],expected,now));
assert.throws(()=>selectNewSite([{...site,capabilities:{}}],expected,now));
const base='https://playground-wpcom-connect.netlify.app';
const account={token:'test-token',flow:'flow',exp:now+60000};
const cookie='__Host-pgwpc-account='+seal(account);
const proof=seal({purpose:'watch',flow:'flow',exp:account.exp});
const request=(action,headers={},body={})=>new Request(base+'/api/new-site?action='+action,{method:'POST',headers:{cookie,...headers},body:JSON.stringify(body)});
assert.equal((await handler(request('prepare'))).status,403);
globalThis.fetch=async()=>Response.json({sites:[]});
const prepared=await handler(request('prepare',{'x-pgwpc-watch':proof},{name:'newsite'}));
assert.equal(prepared.status,200);
const watch=prepared.headers.get('set-cookie').split(';')[0];
globalThis.fetch=async()=>Response.json({sites:[site]});
const polled=await handler(request('poll',{'x-pgwpc-watch':proof,cookie:cookie+'; '+watch}));
assert.equal((await polled.json()).ready,true);
assert.match(polled.headers.get('set-cookie'),/__Host-pgwpc-session=/);
const existing=await handler(request('prepare',{'x-pgwpc-watch':proof},{name:'newsite'}));
assert.equal(existing.status,409);
const start=await handler(new Request(base+'/oauth/wordpress/start?mode=new'));
assert.equal(new URL(start.headers.get('location')).searchParams.get('scope'),'global');
console.log('PASS: new-site matching, old/ambiguous/non-admin rejection, paid-plan waiting, CSRF and session handoff.');
